const mockTotalData =
{
    "burgers": [
        {
            "id": 48,
            "name": "허니갈릭 스테이크버거",
            "description": "달콤한 허니와 풍부한 갈릭 향의 스테이크 버거",
            "price": 8000,
            "calory": 780,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 305,
            "spicy": 0,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:50:27.000Z",
            "allergies": [
                "난류",
                "대두",
                "밀",
                "쇠고기",
                "우유"
            ]
        },
        {
            "id": 33,
            "name": "스모키 바베큐 버거",
            "description": "훈제향 가득한 바베큐 소스의 풍미가 일품인 버거",
            "price": 6900,
            "calory": 740,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 270,
            "spicy": 0,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:50:27.000Z",
            "allergies": [
                "난류",
                "대두",
                "밀",
                "쇠고기",
                "우유",
                "토마토"
            ]
        },
        {
            "id": 34,
            "name": "트러플 머쉬룸 버거",
            "description": "고급스러운 트러플 향과 버섯의 조화가 일품인 버거",
            "price": 7800,
            "calory": 760,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 290,
            "spicy": 2,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:52:18.000Z",
            "allergies": [
                "난류",
                "대두",
                "밀",
                "버섯",
                "우유",
                "토마토"
            ]
        },
        {
            "id": 35,
            "name": "차돌박이 치즈버거",
            "description": "부드러운 차돌박이와 치즈의 환상적인 조화",
            "price": 8300,
            "calory": 800,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 310,
            "spicy": 1,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:52:18.000Z",
            "allergies": [
                "난류",
                "대두",
                "밀",
                "쇠고기",
                "우유"
            ]
        },
        {
            "id": 36,
            "name": "고추장 비프버거",
            "description": "매콤달콤한 고추장 소스와 비프 패티의 조화",
            "price": 6500,
            "calory": 640,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 260,
            "spicy": 2,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:55:14.000Z",
            "allergies": [
                "난류",
                "대두",
                "밀",
                "쇠고기",
                "우유"
            ]
        },
        {
            "id": 37,
            "name": "불닭 버거",
            "description": "전국민이 사랑하는 불닭 소스를 활용한 매운 치킨 버거",
            "price": 5000,
            "calory": 550,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 230,
            "spicy": 2,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:55:14.000Z",
            "allergies": [
                "난류",
                "닭고기",
                "대두",
                "밀",
                "우유"
            ]
        },
        {
            "id": 38,
            "name": "페퍼로니 피자 버거",
            "description": "피자의 맛을 그대로 담아낸 특별한 버거",
            "price": 7200,
            "calory": 730,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 280,
            "spicy": 1,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:52:18.000Z",
            "allergies": [
                "난류",
                "대두",
                "돼지고기",
                "밀",
                "우유"
            ]
        },
        {
            "id": 39,
            "name": "콰트로 치즈버거",
            "description": "네 가지 치즈의 풍미를 한번에 즐기는 버거",
            "price": 8500,
            "calory": 820,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 320,
            "spicy": 1,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:52:18.000Z",
            "allergies": [
                "난류",
                "대두",
                "밀",
                "쇠고기",
                "우유"
            ]
        },
        {
            "id": 40,
            "name": "할라피뇨 치킨버거",
            "description": "알싸한 할라피뇨와 치킨의 매콤한 조화",
            "price": 5900,
            "calory": 560,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 220,
            "spicy": 2,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:55:14.000Z",
            "allergies": [
                "난류",
                "닭고기",
                "대두",
                "밀",
                "우유",
                "할라피뇨"
            ]
        },
        {
            "id": 41,
            "name": "고구마 머핀 버거",
            "description": "달콤한 고구마 패티가 들어간 독특한 버거",
            "price": 4900,
            "calory": 470,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 180,
            "spicy": 0,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:50:27.000Z",
            "allergies": [
                "고구마",
                "난류",
                "대두",
                "밀",
                "쇠고기",
                "우유"
            ]
        },
        {
            "id": 42,
            "name": "썬드라이 토마토 버거",
            "description": "달콤酸한 썬드라이 토마토가 들어간 색다른 버거",
            "price": 4400,
            "calory": 410,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 160,
            "spicy": 0,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:50:27.000Z",
            "allergies": [
                "난류",
                "대두",
                "밀",
                "우유",
                "토마토"
            ]
        },
        {
            "id": 43,
            "name": "양송이 버섯버거",
            "description": "풍부한 양송이 향이 가득한 버섯 버거",
            "price": 6300,
            "calory": 610,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 250,
            "spicy": 0,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:50:27.000Z",
            "allergies": [
                "난류",
                "대두",
                "밀",
                "버섯",
                "쇠고기",
                "우유"
            ]
        },
        {
            "id": 44,
            "name": "키위 버거",
            "description": "상큼한 키위 소스가 들어간 이색 버거",
            "price": 5400,
            "calory": 530,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 205,
            "spicy": 0,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:50:27.000Z",
            "allergies": [
                "난류",
                "대두",
                "밀",
                "쇠고기",
                "우유",
                "키위"
            ]
        },
        {
            "id": 45,
            "name": "매콤한 새우버거",
            "description": "매콤한 소스와 새우 패티의 짭짤한 조화",
            "price": 6200,
            "calory": 590,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 235,
            "spicy": 1,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:55:14.000Z",
            "allergies": [
                "난류",
                "대두",
                "밀",
                "새우",
                "우유"
            ]
        },
        {
            "id": 46,
            "name": "스위스 치즈 버거",
            "description": "구멍 숭숭 스위스 치즈의 독특한 맛이 일품인 버거",
            "price": 7400,
            "calory": 710,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 265,
            "spicy": 1,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:52:18.000Z",
            "allergies": [
                "난류",
                "대두",
                "밀",
                "쇠고기",
                "스위스 치즈",
                "우유"
            ]
        },
        {
            "id": 47,
            "name": "아보카도 베이컨버거",
            "description": "부드러운 아보카도와 바삭한 베이컨의 만남",
            "price": 7200,
            "calory": 700,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 255,
            "spicy": 0,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:50:27.000Z",
            "allergies": [
                "난류",
                "대두",
                "돼지고기",
                "밀",
                "아보카도",
                "우유"
            ]
        },
        {
            "id": 32,
            "name": "크림 치즈 버거",
            "description": "부드러운 크림치즈가 들어간 고급스러운 버거",
            "price": 7100,
            "calory": 720,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 255,
            "spicy": 1,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:52:17.000Z",
            "allergies": [
                "난류",
                "대두",
                "밀",
                "쇠고기",
                "우유"
            ]
        },
        {
            "id": 49,
            "name": "카레 치킨 버거",
            "description": "이국적인 카레 풍미가 가득한 치킨 버거",
            "price": 5500,
            "calory": 520,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 210,
            "spicy": 1,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:55:14.000Z",
            "allergies": [
                "난류",
                "닭고기",
                "대두",
                "밀",
                "우유",
                "토마토"
            ]
        },
        {
            "id": 50,
            "name": "랍스터 씨푸드 버거",
            "description": "고급스러운 랍스터 살이 들어간 프리미엄 버거",
            "price": 8900,
            "calory": 860,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 330,
            "spicy": 0,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:50:28.000Z",
            "allergies": [
                "난류",
                "대두",
                "랍스터",
                "밀",
                "우유"
            ]
        },
        {
            "id": 51,
            "name": "멕시칸 칠리 버거",
            "description": "매콤한 멕시칸 칠리 소스가 들어간 이국적인 버거",
            "price": 7700,
            "calory": 740,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 290,
            "spicy": 2,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:55:14.000Z",
            "allergies": [
                "난류",
                "대두",
                "멕시칸 칠리",
                "밀",
                "쇠고기",
                "우유"
            ]
        },
        {
            "id": 52,
            "name": "오리엔탈 치킨 버거",
            "description": "동양적인 향신료로 맛을 낸 특별한 치킨 버거",
            "price": 6800,
            "calory": 650,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 245,
            "spicy": 1,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:55:14.000Z",
            "allergies": [
                "난류",
                "닭고기",
                "대두",
                "밀",
                "우유"
            ]
        },
        {
            "id": 53,
            "name": "그릴드 새우버거",
            "description": "불맛 가득한 그릴에 구운 새우 패티 버거",
            "price": 7100,
            "calory": 680,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 255,
            "spicy": 0,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:50:27.000Z",
            "allergies": [
                "난류",
                "대두",
                "밀",
                "새우",
                "우유"
            ]
        },
        {
            "id": 54,
            "name": "머스타드 비프버거",
            "description": "상큼한 머스타드 소스와 비프 패티의 조화",
            "price": 6300,
            "calory": 600,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 240,
            "spicy": 0,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:50:27.000Z",
            "allergies": [
                "난류",
                "대두",
                "밀",
                "쇠고기",
                "우유"
            ]
        },
        {
            "id": 55,
            "name": "버팔로 치킨 버거",
            "description": "매콤한 버팔로 윙 소스를 활용한 치킨 버거",
            "price": 6100,
            "calory": 580,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 225,
            "spicy": 1,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:55:14.000Z",
            "allergies": [
                "난류",
                "닭고기",
                "대두",
                "밀",
                "우유",
                "토마토"
            ]
        },
        {
            "id": 56,
            "name": "페퍼 스테이크 버거",
            "description": "알싸한 후추 향이 가득한 스테이크 버거",
            "price": 7900,
            "calory": 760,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 300,
            "spicy": 1,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:55:14.000Z",
            "allergies": [
                "난류",
                "대두",
                "밀",
                "쇠고기",
                "우유"
            ]
        },
        {
            "id": 57,
            "name": "써니사이드 업 버거",
            "description": "상큼한 계란 프라이를 올린 아침 느낌의 버거",
            "price": 6500,
            "calory": 620,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 245,
            "spicy": 0,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:50:28.000Z",
            "allergies": [
                "계란",
                "난류",
                "대두",
                "밀",
                "쇠고기",
                "우유"
            ]
        },
        {
            "id": 58,
            "name": "더블 토마토 터키 버거",
            "description": "신선한 토마토와 담백한 터키 패티의 더블 조화",
            "price": 7300,
            "calory": 700,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 275,
            "spicy": 0,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:50:28.000Z",
            "allergies": [
                "난류",
                "대두",
                "밀",
                "우유",
                "칠면조",
                "토마토"
            ]
        },
        {
            "id": 59,
            "name": "포르치니 버거",
            "description": "고급스러운 포르치니 버섯 향이 가득한 버거",
            "price": 7500,
            "calory": 720,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 280,
            "spicy": 0,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:50:28.000Z",
            "allergies": [
                "난류",
                "대두",
                "밀",
                "버섯",
                "우유"
            ]
        },
        {
            "id": 60,
            "name": "블루치즈 버거",
            "description": "진한 블루치즈의 향과 맛이 일품인 버거",
            "price": 8200,
            "calory": 790,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 310,
            "spicy": 0,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:50:27.000Z",
            "allergies": [
                "난류",
                "대두",
                "밀",
                "블루치즈",
                "쇠고기",
                "우유"
            ]
        },
        {
            "id": 61,
            "name": "마늘 버터 쇠고기 버거",
            "description": "香긋한 마늘 버터 소스와 쇠고기의 완벽한 조화",
            "price": 8400,
            "calory": 810,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 315,
            "spicy": 0,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:50:28.000Z",
            "allergies": [
                "난류",
                "대두",
                "밀",
                "쇠고기",
                "우유"
            ]
        },
        {
            "id": 62,
            "name": "바실리코 치킨 버거",
            "description": "신선한 바질 향이 가득한 이탈리안 스타일 치킨 버거",
            "price": 6900,
            "calory": 660,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 250,
            "spicy": 0,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:50:27.000Z",
            "allergies": [
                "난류",
                "닭고기",
                "대두",
                "밀",
                "우유"
            ]
        },
        {
            "id": 63,
            "name": "모로칸 램 버거",
            "description": "이국적인 모로코 향신료로 맛을 낸 양고기 버거",
            "price": 8700,
            "calory": 840,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 325,
            "spicy": 1,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:55:14.000Z",
            "allergies": [
                "난류",
                "대두",
                "밀",
                "양고기",
                "우유"
            ]
        },
        {
            "id": 17,
            "name": "사각새우더블버거",
            "description": "네모난 모양의 특별한 새우 패티가 두 장 들어간 버거",
            "price": 5700,
            "calory": 556,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 208,
            "spicy": 0,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:50:27.000Z",
            "allergies": [
                "난류",
                "대두",
                "밀",
                "새우",
                "우유",
                "토마토"
            ]
        },
        {
            "id": 2,
            "name": "오징어 얼라이브 버거(갈릭맛)",
            "description": "신선한 오징어와 풍부한 갈릭 소스의 조화가 일품인 버거",
            "price": 5500,
            "calory": 502,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 202,
            "spicy": 0,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:50:28.000Z",
            "allergies": [
                "난류",
                "닭고기",
                "대두",
                "밀",
                "새우",
                "쇠고기",
                "오징어",
                "토마토"
            ]
        },
        {
            "id": 3,
            "name": "오징어 얼라이브 비프버거(매운맛)",
            "description": "오징어와 비프 패티가 만나 매콤한 맛을 선사하는 버거",
            "price": 5700,
            "calory": 498,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 187,
            "spicy": 2,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:55:14.000Z",
            "allergies": [
                "난류",
                "닭고기",
                "대두",
                "밀",
                "쇠고기",
                "오징어",
                "토마토"
            ]
        },
        {
            "id": 4,
            "name": "오징어 얼라이브 비프버거(갈릭맛)",
            "description": "오징어와 비프 패티, 갈릭 소스의 환상적인 조합",
            "price": 5700,
            "calory": 479,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 187,
            "spicy": 0,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:50:27.000Z",
            "allergies": [
                "난류",
                "대두",
                "밀",
                "쇠고기",
                "오징어",
                "우유",
                "토마토"
            ]
        },
        {
            "id": 5,
            "name": "전주 비빔라이스 버거",
            "description": "전주 비빔밥을 모티브로 한 독특한 맛의 버거",
            "price": 6900,
            "calory": 572,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 285,
            "spicy": 1,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:52:18.000Z",
            "allergies": [
                "난류",
                "대두",
                "밀",
                "쇠고기"
            ]
        },
        {
            "id": 6,
            "name": "새우베이컨버거",
            "description": "풍부한 새우 맛과 바삭한 베이컨의 조화가 일품인 버거",
            "price": 5800,
            "calory": 538,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 211,
            "spicy": 0,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:50:27.000Z",
            "allergies": [
                "난류",
                "대두",
                "돼지고기",
                "밀",
                "새우",
                "우유",
                "토마토"
            ]
        },
        {
            "id": 7,
            "name": "불고기 베이컨",
            "description": "한국적인 불고기 맛과 서양의 베이컨이 만난 퓨전 버거",
            "price": 5800,
            "calory": 522,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 220,
            "spicy": 0,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:50:28.000Z",
            "allergies": [
                "난류",
                "닭고기",
                "대두",
                "돼지고기",
                "밀",
                "쇠고기",
                "우유",
                "토마토"
            ]
        },
        {
            "id": 8,
            "name": "더블 한우불고기",
            "description": "고급스러운 한우 패티가 두 장 들어간 프리미엄 버거",
            "price": 12400,
            "calory": 802,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 352,
            "spicy": 0,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:50:27.000Z",
            "allergies": [
                "난류",
                "대두",
                "밀",
                "쇠고기",
                "우유",
                "토마토"
            ]
        },
        {
            "id": 9,
            "name": "한우불고기",
            "description": "부드러운 한우 패티로 만든 정통 불고기 버거",
            "price": 8400,
            "calory": 572,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 263,
            "spicy": 1,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:52:18.000Z",
            "allergies": [
                "난류",
                "대두",
                "밀",
                "쇠고기",
                "우유",
                "토마토"
            ]
        },
        {
            "id": 10,
            "name": "더블 클래식치즈버거(버터번)",
            "description": "풍부한 치즈와 버터번의 고소한 맛이 일품인 더블 버거",
            "price": 6900,
            "calory": 731,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 213,
            "spicy": 0,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:50:27.000Z",
            "allergies": [
                "난류",
                "대두",
                "밀",
                "쇠고기",
                "우유"
            ]
        },
        {
            "id": 11,
            "name": "더블 치킨버거",
            "description": "두 장의 바삭한 치킨 패티가 들어간 풍성한 버거",
            "price": 5500,
            "calory": 478,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 205,
            "spicy": 2,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:52:18.000Z",
            "allergies": [
                "난류",
                "닭고기",
                "대두",
                "땅콩",
                "밀",
                "쇠고기",
                "우유",
                "조개류"
            ]
        },
        {
            "id": 12,
            "name": "더블 데리버거",
            "description": "달콤한 데리소스와 두 장의 패티의 완벽한 조화",
            "price": 4500,
            "calory": 446,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 170,
            "spicy": 1,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:52:18.000Z",
            "allergies": [
                "난류",
                "닭고기",
                "대두",
                "밀",
                "쇠고기",
                "우유",
                "조개류"
            ]
        },
        {
            "id": 13,
            "name": "빅불",
            "description": "큼직한 사이즈와 풍부한 불고기 맛이 특징인 버거",
            "price": 7100,
            "calory": 757,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 270,
            "spicy": 0,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:50:27.000Z",
            "allergies": [
                "난류",
                "대두",
                "밀",
                "쇠고기",
                "우유"
            ]
        },
        {
            "id": 14,
            "name": "불고기버거",
            "description": "한국인의 입맛에 딱 맞는 전통적인 불고기 버거",
            "price": 4700,
            "calory": 476,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 188,
            "spicy": 0,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:50:27.000Z",
            "allergies": [
                "난류",
                "닭고기",
                "대두",
                "돼지고기",
                "밀",
                "쇠고기",
                "우유",
                "토마토"
            ]
        },
        {
            "id": 15,
            "name": "모짜렐라 인 더 버거 베이컨",
            "description": "녹진한 모짜렐라 치즈와 베이컨의 환상적인 만남",
            "price": 7400,
            "calory": 699,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 223,
            "spicy": 1,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:52:18.000Z",
            "allergies": [
                "난류",
                "대두",
                "돼지고기",
                "밀",
                "쇠고기",
                "우유"
            ]
        },
        {
            "id": 16,
            "name": "DoubleX2",
            "description": "패티 두 장에 치즈까지 듬뿍 들어간 풍성한 버거",
            "price": 6800,
            "calory": 712,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 228,
            "spicy": 1,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:52:18.000Z",
            "allergies": [
                "난류",
                "대두",
                "밀",
                "쇠고기",
                "우유",
                "토마토"
            ]
        },
        {
            "id": 1,
            "name": "오징어 얼라이브 버거(매운맛)",
            "description": "신선한 오징어와 매콤한 소스가 어우러진 특별한 버거",
            "price": 5500,
            "calory": 502,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 202,
            "spicy": 2,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:55:14.000Z",
            "allergies": [
                "난류",
                "닭고기",
                "대두",
                "밀",
                "새우",
                "쇠고기",
                "오징어",
                "토마토"
            ]
        },
        {
            "id": 18,
            "name": "새우버거",
            "description": "신선한 새우로 만든 패티가 들어간 고소한 버거",
            "price": 4700,
            "calory": 492,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 179,
            "spicy": 0,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:50:27.000Z",
            "allergies": [
                "난류",
                "대두",
                "밀",
                "새우",
                "우유",
                "토마토"
            ]
        },
        {
            "id": 19,
            "name": "리아미라클 Ⅱ",
            "description": "식물성 패티로 만든 건강하고 맛있는 버거",
            "price": 5200,
            "calory": 352,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 181,
            "spicy": 0,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:50:27.000Z",
            "allergies": [
                "대두",
                "밀",
                "토마토"
            ]
        },
        {
            "id": 20,
            "name": "더블리아미라클 Ⅱ",
            "description": "두 장의 식물성 패티로 더욱 풍성해진 채식 버거",
            "price": 6700,
            "calory": 520,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 245,
            "spicy": 0,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:50:27.000Z",
            "allergies": [
                "대두",
                "밀",
                "토마토"
            ]
        },
        {
            "id": 21,
            "name": "핫크리스피버거",
            "description": "바삭하고 매콤한 치킨 패티가 특징인 버거",
            "price": 5900,
            "calory": 503,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 190,
            "spicy": 2,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:55:14.000Z",
            "allergies": [
                "난류",
                "닭고기",
                "대두",
                "밀",
                "토마토"
            ]
        },
        {
            "id": 22,
            "name": "클래식치즈버거(버터번)",
            "description": "고소한 버터번과 치즈의 클래식한 조화",
            "price": 5200,
            "calory": 490,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 146,
            "spicy": 0,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:50:27.000Z",
            "allergies": [
                "난류",
                "대두",
                "밀",
                "쇠고기",
                "우유"
            ]
        },
        {
            "id": 23,
            "name": "T-REX",
            "description": "육식 공룡처럼 큼직한 치킨 패티가 특징인 버거",
            "price": 4700,
            "calory": 475,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 213,
            "spicy": 1,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:52:18.000Z",
            "allergies": [
                "난류",
                "닭고기",
                "대두",
                "땅콩",
                "밀",
                "우유"
            ]
        },
        {
            "id": 24,
            "name": "치킨버거",
            "description": "간단하지만 맛있는 전통적인 치킨 버거",
            "price": 4000,
            "calory": 355,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 141,
            "spicy": 0,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:50:27.000Z",
            "allergies": [
                "난류",
                "닭고기",
                "대두",
                "땅콩",
                "밀",
                "우유",
                "조개류"
            ]
        },
        {
            "id": 25,
            "name": "데리버거",
            "description": "달콤한 데리소스가 들어간 가장 기본적인 버거",
            "price": 3300,
            "calory": 348,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 134,
            "spicy": 0,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:50:27.000Z",
            "allergies": [
                "난류",
                "닭고기",
                "대두",
                "밀",
                "쇠고기",
                "우유",
                "조개류"
            ]
        },
        {
            "id": 26,
            "name": "더블 스파이시 치킨버거",
            "description": "매콤한 치킨 패티가 두 장 들어간 화끈한 버거",
            "price": 5100,
            "calory": 465,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 210,
            "spicy": 2,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:55:14.000Z",
            "allergies": [
                "난류",
                "닭고기",
                "대두",
                "밀",
                "우유",
                "토마토"
            ]
        },
        {
            "id": 27,
            "name": "베지터블 버거",
            "description": "신선한 야채들로 가득 채운 건강한 버거",
            "price": 4200,
            "calory": 380,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 175,
            "spicy": 0,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:50:27.000Z",
            "allergies": [
                "대두",
                "밀",
                "토마토"
            ]
        },
        {
            "id": 28,
            "name": "더블 치즈 햄버거",
            "description": "치즈 듬뿍, 패티 두 장으로 알차게 즐기는 버거",
            "price": 6200,
            "calory": 690,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 250,
            "spicy": 1,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:52:17.000Z",
            "allergies": [
                "난류",
                "대두",
                "밀",
                "쇠고기",
                "우유"
            ]
        },
        {
            "id": 29,
            "name": "터키 베이컨 버거",
            "description": "담백한 터키 패티와 짭조름한 베이컨의 만남",
            "price": 6600,
            "calory": 580,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 240,
            "spicy": 0,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:50:27.000Z",
            "allergies": [
                "난류",
                "대두",
                "돼지고기",
                "밀",
                "우유",
                "칠면조",
                "토마토"
            ]
        },
        {
            "id": 30,
            "name": "스파이시 불고기 버거",
            "description": "매콤한 양념의 불고기 패티가 들어간 버거",
            "price": 5400,
            "calory": 510,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 200,
            "spicy": 2,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:55:14.000Z",
            "allergies": [
                "난류",
                "대두",
                "밀",
                "쇠고기",
                "우유",
                "토마토"
            ]
        },
        {
            "id": 31,
            "name": "허니 머스타드 치킨버거",
            "description": "달콤한 허니와 상큼한 머스타드의 치킨 버거",
            "price": 5300,
            "calory": 490,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 195,
            "spicy": 0,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:50:27.000Z",
            "allergies": [
                "난류",
                "닭고기",
                "대두",
                "밀",
                "우유",
                "토마토"
            ]
        }
    ],
    "totalCount": 63,
    "pageNum": null,
    "pageLimit": null
}
export default mockTotalData;