const mockRecommenedData = 
{
    "burgers": [
        {
            "id": 37,
            "name": "불닭 버거",
            "description": "전국민이 사랑하는 불닭 소스를 활용한 매운 치킨 버거",
            "price": 5000,
            "calory": 550,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 230,
            "spicy": 2,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:55:14.000Z",
            "allergies": [
                "난류",
                "닭고기",
                "대두",
                "밀",
                "우유"
            ]
        },
        {
            "id": 38,
            "name": "페퍼로니 피자 버거",
            "description": "피자의 맛을 그대로 담아낸 특별한 버거",
            "price": 7200,
            "calory": 730,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 280,
            "spicy": 1,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:52:18.000Z",
            "allergies": [
                "난류",
                "대두",
                "돼지고기",
                "밀",
                "우유"
            ]
        },
        {
            "id": 39,
            "name": "콰트로 치즈버거",
            "description": "네 가지 치즈의 풍미를 한번에 즐기는 버거",
            "price": 8500,
            "calory": 820,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 320,
            "spicy": 1,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:52:18.000Z",
            "allergies": [
                "난류",
                "대두",
                "밀",
                "쇠고기",
                "우유"
            ]
        },
        {
            "id": 40,
            "name": "할라피뇨 치킨버거",
            "description": "알싸한 할라피뇨와 치킨의 매콤한 조화",
            "price": 5900,
            "calory": 560,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 220,
            "spicy": 2,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:55:14.000Z",
            "allergies": [
                "난류",
                "닭고기",
                "대두",
                "밀",
                "우유",
                "할라피뇨"
            ]
        },
        {
            "id": 41,
            "name": "고구마 머핀 버거",
            "description": "달콤한 고구마 패티가 들어간 독특한 버거",
            "price": 4900,
            "calory": 470,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 180,
            "spicy": 0,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:50:27.000Z",
            "allergies": [
                "고구마",
                "난류",
                "대두",
                "밀",
                "쇠고기",
                "우유"
            ]
        },
        {
            "id": 42,
            "name": "썬드라이 토마토 버거",
            "description": "달콤酸한 썬드라이 토마토가 들어간 색다른 버거",
            "price": 4400,
            "calory": 410,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 160,
            "spicy": 0,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:50:27.000Z",
            "allergies": [
                "난류",
                "대두",
                "밀",
                "우유",
                "토마토"
            ]
        },
        {
            "id": 43,
            "name": "양송이 버섯버거",
            "description": "풍부한 양송이 향이 가득한 버섯 버거",
            "price": 6300,
            "calory": 610,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 250,
            "spicy": 0,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:50:27.000Z",
            "allergies": [
                "난류",
                "대두",
                "밀",
                "버섯",
                "쇠고기",
                "우유"
            ]
        },
        {
            "id": 44,
            "name": "키위 버거",
            "description": "상큼한 키위 소스가 들어간 이색 버거",
            "price": 5400,
            "calory": 530,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 205,
            "spicy": 0,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:50:27.000Z",
            "allergies": [
                "난류",
                "대두",
                "밀",
                "쇠고기",
                "우유",
                "키위"
            ]
        },
        {
            "id": 45,
            "name": "매콤한 새우버거",
            "description": "매콤한 소스와 새우 패티의 짭짤한 조화",
            "price": 6200,
            "calory": 590,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 235,
            "spicy": 1,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:55:14.000Z",
            "allergies": [
                "난류",
                "대두",
                "밀",
                "새우",
                "우유"
            ]
        },
        {
            "id": 46,
            "name": "스위스 치즈 버거",
            "description": "구멍 숭숭 스위스 치즈의 독특한 맛이 일품인 버거",
            "price": 7400,
            "calory": 710,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 265,
            "spicy": 1,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:52:18.000Z",
            "allergies": [
                "난류",
                "대두",
                "밀",
                "쇠고기",
                "스위스 치즈",
                "우유"
            ]
        },
        {
            "id": 47,
            "name": "아보카도 베이컨버거",
            "description": "부드러운 아보카도와 바삭한 베이컨의 만남",
            "price": 7200,
            "calory": 700,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 255,
            "spicy": 0,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:50:27.000Z",
            "allergies": [
                "난류",
                "대두",
                "돼지고기",
                "밀",
                "아보카도",
                "우유"
            ]
        },
        {
            "id": 32,
            "name": "크림 치즈 버거",
            "description": "부드러운 크림치즈가 들어간 고급스러운 버거",
            "price": 7100,
            "calory": 720,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 255,
            "spicy": 1,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:52:17.000Z",
            "allergies": [
                "난류",
                "대두",
                "밀",
                "쇠고기",
                "우유"
            ]
        },
        {
            "id": 49,
            "name": "카레 치킨 버거",
            "description": "이국적인 카레 풍미가 가득한 치킨 버거",
            "price": 5500,
            "calory": 520,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 210,
            "spicy": 1,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:55:14.000Z",
            "allergies": [
                "난류",
                "닭고기",
                "대두",
                "밀",
                "우유",
                "토마토"
            ]
        },
        {
            "id": 50,
            "name": "랍스터 씨푸드 버거",
            "description": "고급스러운 랍스터 살이 들어간 프리미엄 버거",
            "price": 8900,
            "calory": 860,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 330,
            "spicy": 0,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:50:28.000Z",
            "allergies": [
                "난류",
                "대두",
                "랍스터",
                "밀",
                "우유"
            ]
        },
        {
            "id": 51,
            "name": "멕시칸 칠리 버거",
            "description": "매콤한 멕시칸 칠리 소스가 들어간 이국적인 버거",
            "price": 7700,
            "calory": 740,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 290,
            "spicy": 2,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:55:14.000Z",
            "allergies": [
                "난류",
                "대두",
                "멕시칸 칠리",
                "밀",
                "쇠고기",
                "우유"
            ]
        },
        {
            "id": 52,
            "name": "오리엔탈 치킨 버거",
            "description": "동양적인 향신료로 맛을 낸 특별한 치킨 버거",
            "price": 6800,
            "calory": 650,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 245,
            "spicy": 1,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:55:14.000Z",
            "allergies": [
                "난류",
                "닭고기",
                "대두",
                "밀",
                "우유"
            ]
        },
        {
            "id": 53,
            "name": "그릴드 새우버거",
            "description": "불맛 가득한 그릴에 구운 새우 패티 버거",
            "price": 7100,
            "calory": 680,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 255,
            "spicy": 0,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:50:27.000Z",
            "allergies": [
                "난류",
                "대두",
                "밀",
                "새우",
                "우유"
            ]
        },
        {
            "id": 54,
            "name": "머스타드 비프버거",
            "description": "상큼한 머스타드 소스와 비프 패티의 조화",
            "price": 6300,
            "calory": 600,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 240,
            "spicy": 0,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:50:27.000Z",
            "allergies": [
                "난류",
                "대두",
                "밀",
                "쇠고기",
                "우유"
            ]
        },
        {
            "id": 55,
            "name": "버팔로 치킨 버거",
            "description": "매콤한 버팔로 윙 소스를 활용한 치킨 버거",
            "price": 6100,
            "calory": 580,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 225,
            "spicy": 1,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:55:14.000Z",
            "allergies": [
                "난류",
                "닭고기",
                "대두",
                "밀",
                "우유",
                "토마토"
            ]
        },
        {
            "id": 56,
            "name": "페퍼 스테이크 버거",
            "description": "알싸한 후추 향이 가득한 스테이크 버거",
            "price": 7900,
            "calory": 760,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 300,
            "spicy": 1,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:55:14.000Z",
            "allergies": [
                "난류",
                "대두",
                "밀",
                "쇠고기",
                "우유"
            ]
        },
        {
            "id": 57,
            "name": "써니사이드 업 버거",
            "description": "상큼한 계란 프라이를 올린 아침 느낌의 버거",
            "price": 6500,
            "calory": 620,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 245,
            "spicy": 0,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:50:28.000Z",
            "allergies": [
                "계란",
                "난류",
                "대두",
                "밀",
                "쇠고기",
                "우유"
            ]
        },
        {
            "id": 60,
            "name": "블루치즈 버거",
            "description": "진한 블루치즈의 향과 맛이 일품인 버거",
            "price": 8200,
            "calory": 790,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 310,
            "spicy": 0,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:50:27.000Z",
            "allergies": [
                "난류",
                "대두",
                "밀",
                "블루치즈",
                "쇠고기",
                "우유"
            ]
        },
        {
            "id": 8,
            "name": "더블 한우불고기",
            "description": "고급스러운 한우 패티가 두 장 들어간 프리미엄 버거",
            "price": 12400,
            "calory": 802,
            "image": null,
            "brand": "롯데리아",
            "managerId": 0,
            "weight": 352,
            "spicy": 0,
            "createdAt": "2024-08-26T06:18:25.000Z",
            "updatedAt": "2024-08-26T08:50:27.000Z",
            "allergies": [
                "난류",
                "대두",
                "밀",
                "쇠고기",
                "우유",
                "토마토"
            ]
        },
    ],
    "totalCount": 63,
    "pageNum": null,
    "pageLimit": null
}

export default mockRecommenedData;